### ISSUE TITLE
Operator installation stalls on CRC (CodeReady Containers)

### ISSUE THREAD

**Issue by andymiller96** [ploigos/ploigos-software-factory-operator#181] opened 2021-05-11 14:16 UTC
### Environment
* CRC for OpenShift 4.7.8
* Fedora 34
### Steps to recreate
1. Install CRC
2.  Follow installation instructions in ploigos-software-factory-operator Readme
3. Operator installation in step 4 (below) stalls with "UpgradePending" status for operator under "Installed Operators" tab
```yaml
oc apply -f - << EOF
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ploigos-software-factory-operator
  namespace: devsecops
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: ploigos-software-factory-operator
  source: redhatgov-operators
  sourceNamespace: openshift-marketplace
EOF
```
### Notes
* Installation via GUI succeeds
* Nothing in event log
* Adding `Starting CSV:           ploigos-software-factory-operator.v0.3.2` to subscription does not resolve issue

**Comment by adamgoossens** [comment] 2021-05-11 21:47
Thanks, we'll take a look. I'll see if I can replicate it on a local CRC instance.

Meanwhile, are there any errors or unsatisfied conditions in the `status` fields for the `Subscription` or `ClusterServiceVersion` in the `devsecops` namespace?

**Comment by adamgoossens** [comment] 2021-05-11 22:32
I think I know what the problem is here. I suspect there is no `OperatorGroup` present in the `devsecops` namespace and so OLM is not watching the namespace for installations.

To solve this problem there are three options:

1. Install PSFO using the OperatorHub in the GUI, because that process causes an `OperatorGroup` to be created and added to `devsecops` when you choose "Install to a specific namespace on the cluster" - this is why GUI installation works for you.
2. Install PSFO cluster-wide, as it will be installed into the `openshift-operators` namespace that has an `OperatorGroup` that targets all namespaces.
3. Create the `OperatorGroup` YAML ahead of time for the `devsecops` namespace.

The following `OperatorGroup` should work:

```
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  namespace: devsecops
  name: devsecops-og
spec:
  targetNamespaces:
    - devsecops
```

We need to adjust the install documentation to include creating an OperatorGroup in the `devsecops` namespace.

**Comment by andymiller96** [comment] 2021-05-12 00:30
> I think I know what the problem is here. I suspect there is no `OperatorGroup` present in the `devsecops` namespace and so OLM is not watching the namespace for installations.
> 
> To solve this problem there are three options:
> 
> 1. Install PSFO using the OperatorHub in the GUI, because that process causes an `OperatorGroup` to be created and added to `devsecops` when you choose "Install to a specific namespace on the cluster" - this is why GUI installation works for you.
> 2. Install PSFO cluster-wide, as it will be installed into the `openshift-operators` namespace that has an `OperatorGroup` that targets all namespaces.
> 3. Create the `OperatorGroup` YAML ahead of time for the `devsecops` namespace.
> 
> The following `OperatorGroup` should work:
> 
> ```
> apiVersion: operators.coreos.com/v1
> kind: OperatorGroup
> metadata:
>   namespace: devsecops
>   name: devsecops-og
> spec:
>   targetNamespaces:
>     - devsecops
> ```
> 
> We need to adjust the install documentation to include creating an OperatorGroup in the `devsecops` namespace.

**Option 3 worked.** 

Option 1 was tested and working prior. I haven't tested option 2.

Since the `oc` cmd line method of installation was in the Readme, I had assumed that this issue was CRC-specific. IOW - I had assumed that the Readme installation instructions would've worked on a regular OCP cluster. Is this not the case?

**Comment by adamgoossens** [comment] 2021-05-12 05:30
To be honest, I suspect the default instructions will not work on a regular OCP cluster. I could be wrong - OLM is still a little bit 'magic' to me - but I've never seen Operator installation work without a corresponding `OperatorGroup`.

Easy enough to test though, and a quick PR to the installation instructions should make the `OperatorGroup` requirement explicit.

**Comment by adamgoossens** [comment] 2021-05-12 08:19
Yeah, I just attempted to follow our instructions on a OCP 4.7 cluster, with no `OperatorGroup`, and I'm stuck in `UpgradePending`.

I'll raise a PR to fix the README.

**Closed** 2021-05-12 11:43 UTC
